
import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Advanced Microeconomics Solution Set',
    description: 'Comprehensive step-by-step solutions for advanced microeconomic modeling, including game theory and general equilibrium analysis.',
    price: 24.99,
    category: 'Business',
    thumbnail: 'https://picsum.photos/seed/micro/600/400',
    fileSize: '4.2 MB',
    pages: 45,
    rating: 4.8,
    salesCount: 124,
    discountLabel: '15% OFF',
    priceHistory: [29.99, 27.50, 24.99]
  },
  {
    id: '2',
    title: 'Quantum Mechanics Exam Prep Guide',
    description: 'A curated set of answers for common quantum physics problems. Covers Schrödinger equation, spin, and perturbation theory.',
    price: 34.50,
    category: 'STEM',
    thumbnail: 'https://picsum.photos/seed/quantum/600/400',
    fileSize: '12.8 MB',
    pages: 82,
    rating: 4.9,
    salesCount: 89,
    isFeatured: true,
    priceHistory: [32.00, 36.00, 34.50]
  },
  {
    id: '3',
    title: 'Full-Stack React Interview Q&A',
    description: 'Complete guide to modern React questions including hooks, suspense, and server components with detailed architectural answers.',
    price: 19.99,
    category: 'Tech',
    thumbnail: 'https://picsum.photos/seed/react/600/400',
    fileSize: '2.5 MB',
    pages: 30,
    rating: 4.7,
    salesCount: 342,
    discountLabel: 'HOT',
    priceHistory: [24.99, 19.99, 19.99]
  },
  {
    id: '4',
    title: 'Corporate Law Case Study Analysis',
    description: 'Deep dive into 50+ landmark corporate law cases with summary of verdicts and legal reasoning.',
    price: 45.00,
    category: 'Humanities',
    thumbnail: 'https://picsum.photos/seed/law/600/400',
    fileSize: '15.1 MB',
    pages: 120,
    rating: 4.6,
    salesCount: 56,
    priceHistory: [40.00, 42.50, 45.00]
  },
  {
    id: '5',
    title: 'Data Structures & Algorithms Cheat Sheet',
    description: 'High-density PDF containing optimized solutions for top 100 LeetCode style problems.',
    price: 15.00,
    category: 'Tech',
    thumbnail: 'https://picsum.photos/seed/algo/600/400',
    fileSize: '1.8 MB',
    pages: 15,
    rating: 5.0,
    salesCount: 1205,
    isFeatured: true,
    priceHistory: [19.99, 17.50, 15.00]
  },
  {
    id: '6',
    title: 'Organic Chemistry II Complete Key',
    description: 'Mechanism walkthroughs and synthesis pathway answers for common organic chemistry curriculum.',
    price: 29.99,
    category: 'STEM',
    thumbnail: 'https://picsum.photos/seed/chem/600/400',
    fileSize: '8.4 MB',
    pages: 64,
    rating: 4.5,
    salesCount: 213,
    discountLabel: 'NEW',
    priceHistory: [29.99, 29.99, 29.99]
  },
  {
    id: '7',
    title: 'Machine Learning Fundamentals Workbook',
    description: 'Detailed derivations and implementations of linear regression, SVM, and Neural Networks from scratch.',
    price: 39.99,
    category: 'Tech',
    thumbnail: 'https://picsum.photos/seed/ml/600/400',
    fileSize: '10.2 MB',
    pages: 95,
    rating: 4.9,
    salesCount: 450,
    priceHistory: [44.99, 42.00, 39.99]
  },
  {
    id: '8',
    title: 'Supply Chain Management Strategy Guide',
    description: 'Strategic answers for logistics optimization and global supply chain resilience modeling.',
    price: 28.50,
    category: 'Business',
    thumbnail: 'https://picsum.photos/seed/supply/600/400',
    fileSize: '5.5 MB',
    pages: 52,
    rating: 4.7,
    salesCount: 167,
    priceHistory: [30.00, 28.50, 28.50]
  },
  {
    id: '9',
    title: 'Ethics in International Relations',
    description: 'Comprehensive analysis of moral dilemmas in modern global politics and humanitarian interventions.',
    price: 22.00,
    category: 'Humanities',
    thumbnail: 'https://picsum.photos/seed/ethics/600/400',
    fileSize: '4.0 MB',
    pages: 40,
    rating: 4.4,
    salesCount: 82,
    priceHistory: [25.00, 24.00, 22.00]
  },
  {
    id: '10',
    title: 'Financial Accounting Master Solutions',
    description: 'Complete worked solutions for balance sheets, income statements, and financial ratio analysis problems.',
    price: 26.99,
    category: 'Business',
    thumbnail: 'https://picsum.photos/seed/accounting/600/400',
    fileSize: '6.3 MB',
    pages: 58,
    rating: 4.6,
    salesCount: 194,
    discountLabel: '10% OFF',
    priceHistory: [29.99, 27.99, 26.99]
  },
  {
    id: '11',
    title: 'Thermodynamics Problem Solver',
    description: 'Step-by-step derivations for entropy, enthalpy, and heat transfer numerical problems.',
    price: 31.50,
    category: 'STEM',
    thumbnail: 'https://picsum.photos/seed/thermo/600/400',
    fileSize: '9.7 MB',
    pages: 72,
    rating: 4.8,
    salesCount: 143,
    priceHistory: [35.00, 33.00, 31.50]
  },
  {
    id: '12',
    title: 'Node.js Backend Architecture Guide',
    description: 'Practical backend patterns including REST APIs, authentication, and scalable project structures.',
    price: 21.99,
    category: 'Tech',
    thumbnail: 'https://picsum.photos/seed/nodejs/600/400',
    fileSize: '3.4 MB',
    pages: 38,
    rating: 4.7,
    salesCount: 389,
    isFeatured: true,
    priceHistory: [25.00, 23.00, 21.99]
  },
  {
    id: '13',
    title: 'Constitutional Law Case Digest',
    description: 'Summarized landmark constitutional cases with issue analysis and final judgments.',
    price: 41.00,
    category: 'Humanities',
    thumbnail: 'https://picsum.photos/seed/constitution/600/400',
    fileSize: '13.2 MB',
    pages: 110,
    rating: 4.5,
    salesCount: 74,
    priceHistory: [38.00, 40.00, 41.00]
  },
  {
    id: '14',
    title: 'Linear Algebra Complete Solutions',
    description: 'Matrix operations, eigenvalues, vector spaces and proof-based solution walkthroughs.',
    price: 27.75,
    category: 'STEM',
    thumbnail: 'https://picsum.photos/seed/linear/600/400',
    fileSize: '7.6 MB',
    pages: 67,
    rating: 4.9,
    salesCount: 256,
    discountLabel: 'BESTSELLER',
    priceHistory: [32.00, 30.00, 27.75]
  },
  {
    id: '15',
    title: 'Digital Marketing Strategy Workbook',
    description: 'SEO, paid ads, funnel optimization and analytics-based marketing decision frameworks.',
    price: 23.50,
    category: 'Business',
    thumbnail: 'https://picsum.photos/seed/marketing/600/400',
    fileSize: '4.8 MB',
    pages: 49,
    rating: 4.6,
    salesCount: 301,
    priceHistory: [26.00, 24.50, 23.50]
  },
  {
    id: '16',
    title: 'Python for Data Analysis Handbook',
    description: 'Pandas, NumPy, and data visualization exercises with fully explained solutions.',
    price: 18.99,
    category: 'Tech',
    thumbnail: 'https://picsum.photos/seed/python/600/400',
    fileSize: '2.9 MB',
    pages: 34,
    rating: 4.8,
    salesCount: 520,
    discountLabel: 'HOT',
    priceHistory: [22.00, 20.00, 18.99]
  },
  {
    id: '17',
    title: 'Macroeconomics Policy Analysis Guide',
    description: 'Fiscal and monetary policy modeling with IS-LM and AD-AS frameworks explained.',
    price: 24.00,
    category: 'Business',
    thumbnail: 'https://picsum.photos/seed/macro/600/400',
    fileSize: '5.1 MB',
    pages: 46,
    rating: 4.5,
    salesCount: 132,
    priceHistory: [27.00, 25.50, 24.00]
  },
  {
    id: '18',
    title: 'Artificial Intelligence Concepts Explained',
    description: 'Search algorithms, knowledge representation, and intelligent agents with worked examples.',
    price: 36.99,
    category: 'Tech',
    thumbnail: 'https://picsum.photos/seed/ai/600/400',
    fileSize: '11.4 MB',
    pages: 88,
    rating: 4.9,
    salesCount: 410,
    isFeatured: true,
    priceHistory: [40.00, 38.00, 36.99]
  },
  {
    id: '19',
    title: 'World History Analytical Essays',
    description: 'Structured essays on major global events with argument development techniques.',
    price: 19.50,
    category: 'Humanities',
    thumbnail: 'https://picsum.photos/seed/history/600/400',
    fileSize: '3.7 MB',
    pages: 36,
    rating: 4.3,
    salesCount: 97,
    priceHistory: [21.00, 20.00, 19.50]
  },
  {
    id: '20',
    title: 'Cybersecurity Fundamentals Playbook',
    description: 'Network security, encryption basics, and penetration testing case scenarios.',
    price: 33.00,
    category: 'Tech',
    thumbnail: 'https://picsum.photos/seed/security/600/400',
    fileSize: '9.0 MB',
    pages: 76,
    rating: 4.8,
    salesCount: 278,
    discountLabel: 'NEW',
    priceHistory: [36.00, 34.50, 33.00]
  }
];
